### ISSUE TITLE
Know the revealed row

### ISSUE THREAD

**Issue by fabiosoft** [alexzielenski/ZKRevealingTableViewCell#12]
How can I catch what row is revealed? I need to send parameters to my custom back view and run methods with parameters tapping some uibuttons.

**Comment by alexzielenski** [comment]
https://github.com/alexzielenski/ZKRevealingTableViewCell/blob/master/ZKRevealingTableViewCell/ZKRevealingTableViewController.m#L94

http://developer.apple.com/library/ios/documentation/uikit/reference/UITableView_Class/Reference/Reference.html#//apple_ref/occ/instm/UITableView/indexPathForCell:
