### ISSUE TITLE
No support for cells with alternating row colors

### ISSUE THREAD

**Issue by ekdevdes** [alexzielenski/ZKRevealingTableViewCell#2]
I like this project for its simplicity, I think it's the easiest way to get this kind of feature in an iOS app. My only gripe is that it doesn't support cells with alternating row colors. I tried using this in my current project (which has alternating row colors for the cells)  and it turned every cell the same color and made the backgroundViews of the textLabels that naturally come with a cell, gray. By alternating row colors I mean that all even numbered cells in each row are one color and all the odd numbered cells are another color. Kinda like the app store's tableView. I would like to use this in my latest project, Fiddles (the first ever jsFiddle client for iOS) but I need ZKRevealingTableViewCell to Support alternate row colors. 

Currently [this](http://amychr.wordpress.com/2010/05/30/uiceil-backgrounds-and-alternating-row-color-in-uitableview/) is the way I am implementing alternate row colors. If you need more information to fix this issue please let me know

**Comment by alexzielenski** [comment]
The problem is [#L86](https://github.com/alexzielenski/ZKRevealingTableViewCell/blob/master/vendor/ZKRevealingTableViewCell.m#L86). The background color of the contentView is set so that the background view does not appear on the edges of the cell. When you set your background color of the cell itself, you must also set that background color to the contentView like this:

``` objc
- (void)tableView:(UITableView *)tableView willDisplayCell:(UITableViewCell *)cell forRowAtIndexPath:(NSIndexPath *)indexPath {
   NSUInteger row = [indexPath row];
   if (row % 2 == 0) {
      cell.backgroundColor = [UIColor whiteColor];
   } else {
      cell.backgroundColor = [UIColor colorWithRed:0.892 green:0.893 blue:0.892 alpha:1.0];
   }

   cell.contentView.backgroundColor = cell.backgroundColor;
}
```

I implemented this really quickly in the test app and got what I think is the effect that you're going for:

![](http://cl.ly/GdSP/Screen%20Shot%202012-05-15%20at%203.27.12%20PM.png)

**Comment by alexzielenski** [comment]
Also, I added the code to the demo in the repository.

**Comment by ekdevdes** [comment]
I'll try it thanks

**Comment by ekdevdes** [comment]
It worked. Thanks.

**Comment by BlackMarq20** [comment]
Hi,

I'm trying to have a custom background for my cell and then a different colored background for the view behind the cell, how would I do this? Also, is it possible to add controls to the backview? do you have any examples of this?

**Comment by BlackMarq20** [comment]
Ok I was able to fix the background issue, now the cells are allowing me to swipe more than one and they also don't close back when scrolling. I copied the code from your example in which it exhibits this behavior, in my project on my custom cell it's not working properly. Any ideas before posting an issue?
