### ISSUE TITLE
backview showing through on front during selection

### ISSUE THREAD

**Issue by BlackMarq20** [alexzielenski/ZKRevealingTableViewCell#6]
When buttons or labels are loaded to the backview, and a selection on the cell is made, the backview items (buttons and labels) show through on the front view.

**Comment by jacobcaraballo** [comment]
// .h
@property (nonatomic, strong) UITableViewCell *theCell;

// .m
@synthesize theCell = _theCell;

//in tableView : cellForRowAtIndexPath disable cell selection by implementing the following
          cell.selectionStyle = UITableViewCellSelectionStyleNone;

//then highlight the cell yourself with the following
- (void)tableView:(UITableView *)tableView didHighlightRowAtIndexPath:(NSIndexPath *)indexPath {
  _theCell = [tableView cellForRowAtIndexPath:indexPath];
  [self setCellColor:[UIColor whiteColor] ForCell:_theCell]; //highlight color
  }
- (void)tableView:(UITableView *)tableView didUnhighlightRowAtIndexPath:(NSIndexPath *)indexPath {
  [self setCellColor:[UIColor colorWithWhite:0.961 alpha:1.000] ForCell:_theCell]; //normal color
  _theCell = nil;
  }
- (void)setCellColor:(UIColor *)color ForCell:(UITableViewCell *)cell {
  cell.contentView.backgroundColor = color;
  cell.backgroundColor = color;
  }

**Comment by BlackMarq20** [comment]
thanks for the reply back, but these methods are only available with iOS 6, do you know what would be used for 5.0?

**Comment by sidwyn** [comment]
Try tableview.allowsSelection = NO. That worked for me.

**Comment by abbood** [comment]
@hyperous are you serious? that basically means a user cannot select a row! lol

**Comment by xzeror** [comment]
Try code from my fork of this repo. This problem fixed there.

**Comment by alexzielenski** [comment]
108b3afb8416a15bd6393f14a025482c6179ebf3
